layout_spectrum: 0.6016045373398811
typography_spectrum: 0.7895236855838448
color:
  brandStrength: 0.21585137187503278
  lightness: 0.007687259931117296
  saturation: 0.4427235876210034
  rhythmicContrast: 0.21677461150102317
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
name: Corrective Works
